version: '3'
services:
  ocr-server:
      image: node:11
      volumes:
        - .:/app
      working_dir: /app
      command: npm install
      command: npx pm2 start ecosystem.config.js --no-daemon
      ports:
        - 9002:9002